version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    command: python bot.py

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./web:/app/web
    env_file:
      - .env
    ports:
      - "5000:5000"
    command: python web_server.py

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: